### PR TITLE
Build with Vite

### PR DESCRIPTION
**Pull request by robintown**
Vite is a significantly faster builder than Webpack which the JS ecosystem seems to be adopting widely. We're already using it successfully for Compound Web, and Storybook makes it pretty simple to swap it out for Webpack, so that's what I've done here.

### CODE REVIEW

**Review by pixlwave — APPROVED** [review]
Probably worth getting another review from someone on Web. Other than Cloudflare failing this looks fine to me, but I can't say I really know what I'm looking at 🙈

**Comment by benbz** [comment]
As per discussion with @dbkr the Cloudflare failure is because vite requires a newer version of Node than we have configured. https://gitlab.matrix.org/infrastructure/cloudflare/-/merge_requests/232 to change this in preview, will also need changing in production once confirmed it works and is safe to do

**Comment by robintown** [comment]
@benbz Can we go ahead and change the Node version in production? The preview is working, so I'm ready to merge this once production is updated.

**Comment by benbz** [comment]
https://gitlab.matrix.org/infrastructure/cloudflare/-/merge_requests/236 for production. Good for me to merge and apply

**Pull request merged**
